version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t core-data-modules .
      - run:
          name: Create Docker container
          command: |
            mkdir -p ~/test-results

            docker container create \
              --name core-data-container \
              --mount type=bind,source=~/test-results/unittest,target=/app/unittest/
              core-data-modules
      - run:
          name: Run tests
          command: |
            docker start -a core-data-container
#      - run:
#          name: Copy test results from Docker (subdir)
#          command: |
#            mkdir -p ~/test-results/unittest
#            docker cp core-data-container:/app/test_results.xml ~/test-results/unittest/results.xml
      - store_test_results:
          path: ~/test-results
