version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t core-data-modules .
      - run:
          name: Create Docker container
          command: docker container create --name core-data-container core-data-modules
      - run:
          name: Run tests
          command: |
            mkdir -p ~/test-results/unittest
            (docker start -a core-data-container; EXITCODE=$?) || exit 0
            docker cp core-data-container:/app/test_results.xml ~/test-results/unittest/results.xml
            exit $EXITCODE
      - store_test_results:
          path: /test-results
