version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t core-data-modules .
      - run:
          name: Create Docker container
          command: docker container create core-data-container
      - run:
          name: Run tests
          command: docker start -a core-data-container
      - run:
          name: Copy test results out of Docker
          command: docker cp core-data-container:/app/test_results.xml ~/test_results/unittest.xml
      - store_test_results:
          path: ~/test_results
