version: 2.1
commands:
  test-python:
    parameters:
      python-version:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t core-data-modules --build-arg PYTHON_VERSION=<<parameters.python-version>> .
      - run:
          name: Create Docker container # Inner Container (the core data container)
          command: docker container create --name core-data-container core-data-modules
      - run:
          name: Run tests
          command: docker start -a core-data-container
      - run:
          name: Copy test results
          command: |
            mkdir -p ~/test-results/unittest
            docker cp core-data-container:/app/test_results.xml ~/test-results/unittest/results.xml
          when: always
      - store_test_results:
          path: ~/test-results
jobs:
  py-3-6:
    docker:
      - image: cimg/base:2020.01
    steps:
      - test-python:
          python-version: "3.6"
  py-3-7:
    docker:
      - image: cimg/base:2020.01
    steps:
      - test-python:
          python-version: "3.7"
  py-3-8:
    docker:
      - image: cimg/base:2020.01
    steps:
      - test-python:
          python-version: "3.8"
workflows:
  version: 2
  build-and-test:
    jobs:
      - py-3-6
      - py-3-7
      - py-3-8
