class KenyaCodes(object):
    KENYAN_TELEPHONE = "kenyan telephone"

    # Counties
    BARINGO = "baringo"
    BOMET = "bomet"
    BUNGOMA = "bungoma"
    BUSIA = "busia"
    ELGEYO_MARAKWET = "elgeyo marakwet"
    EMBU = "embu"
    GARISSA = "garissa"
    HOMA_BAY = "homa bay"
    ISIOLO = "isiolo"
    KAJIADO = "kajiado"
    KAKAMEGA = "kakamega"
    KERICHO = "kericho"
    KIAMBU = "kiambu"
    KILIFI = "kilifi"
    KIRINYAGA = "kirinyaga"
    KISII = "kisii"
    KISUMU = "kisumu"
    KITUI = "kitui"
    KWALE = "kwale"
    LAIKIPIA = "laikipia"
    LAMU = "lamu"
    MACHAKOS = "machakos"
    MAKUENI = "makueni"
    MANDERA = "mandera"
    MARSABIT = "marsabit"
    MERU = "meru"
    MIGORI = "migori"
    MOMBASA = "mombasa"
    MURANGA = "muranga"
    NAIROBI = "nairobi"
    NAKURU = "nakuru"
    NANDI = "nandi"
    NAROK = "narok"
    NYAMIRA = "nyamira"
    NYANDARUA = "nyandarua"
    NYERI = "nyeri"
    SAMBURU = "samburu"
    SIAYA = "siaya"
    TAITA_TAVETA = "taita taveta"
    TANA_RIVER = "tana river"
    THARAKA_NITHI = "tharaka nithi"
    TRANS_NZOIA = "trans nzoia"
    TURKANA = "turkana"
    UASIN_GISHU = "uasin gishu"
    VIHIGA = "vihiga"
    WAJIR = "wajir"
    WEST_POKOT = "west pokot"

    # Constituencies
    AINABKOI = "ainabkoi"
    AINAMOI = "ainamoi"
    ALDAI = "aldai"
    ALEGO_USONGA = "alego usonga"
    AWENDO = "awendo"
    BAHATI = "bahati"
    BALAMBALA = "balambala"
    BANISSA = "banissa"
    BARINGO_CENTRAL = "baringo central"
    BARINGO_NORTH = "baringo north"
    BARINGO_SOUTH = "baringo south"
    BELGUT = "belgut"
    BOBASI = "bobasi"
    BOMACHOGE_BORABU = "bomachoge borabu"
    BOMACHOGE_CHACHE = "bomachoge chache"
    BOMET_CENTRAL = "bomet central"
    BOMET_EAST = "bomet east"
    BONCHARI = "bonchari"
    BONDO = "bondo"
    BORABU = "borabu"
    BUDALANGI = "budalangi"
    BUMULA = "bumula"
    BURA = "bura"
    BURETI = "bureti"
    BUTERE = "butere"
    BUTULA = "butula"
    BUURI = "buuri"
    CENTRAL_IMENTI = "central imenti"
    CHANGAMWE = "changamwe"
    CHEPALUNGU = "chepalungu"
    CHERANGANY = "cherangany"
    CHESUMEI = "chesumei"
    CHUKA_IGAMBANG_OMBE = "chuka/igambang'ombe"
    DADAAB = "dadaab"
    DAGORETTI_NORTH = "dagoretti north"
    DAGORETTI_SOUTH = "dagoretti south"
    ELDAMA_RAVINE = "eldama ravine"
    ELDAS = "eldas"
    EMBAKASI_CENTRAL = "embakasi central"
    EMBAKASI_EAST = "embakasi east"
    EMBAKASI_NORTH = "embakasi north"
    EMBAKASI_SOUTH = "embakasi south"
    EMBAKASI_WEST = "embakasi west"
    EMGWEN = "emgwen"
    EMUHAYA = "emuhaya"
    EMURUA_DIKIRR = "emurua dikirr"
    ENDEBESS = "endebess"
    FAFI = "fafi"
    FUNYULA = "funyula"
    GALOLE = "galole"
    GANZE = "ganze"
    GARISSA_TOWNSHIP = "garissa township"
    GARSEN = "garsen"
    GATANGA = "gatanga"
    GATUNDU_NORTH = "gatundu north"
    GATUNDU_SOUTH = "gatundu south"
    GEM = "gem"
    GICHUGU = "gichugu"
    GILGIL = "gilgil"
    GITHUNGURI = "githunguri"
    HAMISI = "hamisi"
    HOMA_BAY_TOWN = "homa bay town"
    IGEMBE_CENTRAL = "igembe central"
    IGEMBE_NORTH = "igembe north"
    IGEMBE_SOUTH = "igembe south"
    IJARA = "ijara"
    IKOLOMANI = "ikolomani"
    ISIOLO_NORTH = "isiolo north"
    ISIOLO_SOUTH = "isiolo south"
    JOMVU = "jomvu"
    JUJA = "juja"
    KABETE = "kabete"
    KABONDO_KASIPUL = "kabondo kasipul"
    KABUCHAI = "kabuchai"
    KACHELIBA = "kacheliba"
    KAITI = "kaiti"
    KAJIADO_CENTRAL = "kajiado central"
    KAJIADO_EAST = "kajiado east"
    KAJIADO_NORTH = "kajiado north"
    KAJIADO_SOUTH = "kajiado south"
    KAJIADO_WEST = "kajiado west"
    KALOLENI = "kaloleni"
    KAMUKUNJI = "kamukunji"
    KANDARA = "kandara"
    KANDUYI = "kanduyi"
    KANGEMA = "kangema"
    KANGUNDO = "kangundo"
    KAPENGURIA = "kapenguria"
    KAPSERET = "kapseret"
    KARACHUONYO = "karachuonyo"
    KASARANI = "kasarani"
    KASIPUL = "kasipul"
    KATHIANI = "kathiani"
    KEIYO_NORTH = "keiyo north"
    KEIYO_SOUTH = "keiyo south"
    KESSES = "kesses"
    KHWISERO = "khwisero"
    KIAMBAA = "kiambaa"
    KIAMBU = "kiambu"  # (Shadows county name "kiambu")
    KIBRA = "kibra"
    KIBWEZI_EAST = "kibwezi east"
    KIBWEZI_WEST = "kibwezi west"
    KIENI = "kieni"
    KIGUMO = "kigumo"
    KIHARU = "kiharu"
    KIKUYU = "kikuyu"
    KILGORIS = "kilgoris"
    KILIFI_NORTH = "kilifi north"
    KILIFI_SOUTH = "kilifi south"
    KILOME = "kilome"
    KIMILILI = "kimilili"
    KIMININI = "kiminini"
    KINANGO = "kinango"
    KINANGOP = "kinangop"
    KIPIPIRI = "kipipiri"
    KIPKELION_EAST = "kipkelion east"
    KIPKELION_WEST = "kipkelion west"
    KIRINYAGA_CENTRAL = "kirinyaga central"
    KISAUNI = "kisauni"
    KISUMU_CENTRAL = "kisumu central"
    KISUMU_EAST = "kisumu east"
    KISUMU_WEST = "kisumu west"
    KITUTU_CHACHE_SOUTH = "kitutu chache south"
    KITUI_CENTRAL = "kitui central"
    KITUI_EAST = "kitui east"
    KITUI_RURAL = "kitui rural"
    KITUI_SOUTH = "kitui south"
    KITUI_WEST = "kitui west"
    KITUTU_CHACHE_NORTH = "kitutu chache north"
    KITUTU_MASABA = "kitutu masaba"
    KONOIN = "konoin"
    KURESOI_NORTH = "kuresoi north"
    KURESOI_SOUTH = "kuresoi south"
    KURIA_EAST = "kuria east"
    KURIA_WEST = "kuria west"
    KWANZA = "kwanza"
    LAFEY = "lafey"
    LAGDERA = "lagdera"
    LAIKIPIA_EAST = "laikipia east"
    LAIKIPIA_NORTH = "laikipia north"
    LAIKIPIA_WEST = "laikipia west"
    LAISAMIS = "laisamis"
    LAMU_EAST = "lamu east"
    LAMU_WEST = "lamu west"
    LANG_ATA = "lang'ata"
    LARI = "lari"
    LIKONI = "likoni"
    LIKUYANI = "likuyani"
    LIMURU = "limuru"
    LOIMA = "loima"
    LUANDA = "luanda"
    LUGARI = "lugari"
    LUNGA_LUNGA = "lunga lunga"
    LURAMBI = "lurambi"
    MAARA = "maara"
    MACHAKOS_TOWN = "machakos town"
    MAGARINI = "magarini"
    MAKADARA = "makadara"
    MAKUENI = "makueni"  # (Shadows county name "makueni")
    MALAVA = "malava"
    MALINDI = "malindi"
    MANDERA_EAST = "mandera east"
    MANDERA_NORTH = "mandera north"
    MANDERA_SOUTH = "mandera south"
    MANDERA_WEST = "mandera west"
    MANYATTA = "manyatta"
    MARAGWA = "maragwa"
    MARAKWET_EAST = "marakwet east"
    MARAKWET_WEST = "marakwet west"
    MASINGA = "masinga"
    MATAYOS = "matayos"
    MATHARE = "mathare"
    MATHIRA = "mathira"
    MATHIOYA = "mathioya"
    MATUGA = "matuga"
    MATUNGU = "matungu"
    MATUNGULU = "matungulu"
    MAVOKO = "mavoko"
    MBEERE_NORTH = "mbeere north"
    MBEERE_SOUTH = "mbeere south"
    MBOONI = "mbooni"
    MOGOTIO = "mogotio"
    MOIBEN = "moiben"
    MOLO = "molo"
    MOSOP = "mosop"
    MT_ELGON = "mt. elgon"
    MOYALE = "moyale"
    MSAMBWENI = "msambweni"
    MUHORONI = "muhoroni"
    MUKURWEINI = "mukurweini"
    MUMIAS_EAST = "mumias east"
    MUMIAS_WEST = "mumias west"
    MVITA = "mvita"
    MWALA = "mwala"
    MWATATE = "mwatate"
    MWEA = "mwea"
    MWINGI_CENTRAL = "mwingi central"
    MWINGI_NORTH = "mwingi north"
    MWINGI_WEST = "mwingi west"
    NAIVASHA = "naivasha"
    NAKURU_TOWN_EAST = "nakuru town east"
    NAKURU_TOWN_WEST = "nakuru town west"
    NAMBALE = "nambale"
    NANDI_HILLS = "nandi hills"
    NAROK_EAST = "narok east"
    NAROK_NORTH = "narok north"
    NAROK_SOUTH = "narok south"
    NAROK_WEST = "narok west"
    NAVAKHOLO = "navakholo"
    NDARAGWA = "ndaragwa"
    NDHIWA = "ndhiwa"
    NDIA = "ndia"
    NJORO = "njoro"
    NORTH_HORR = "north horr"
    NORTH_IMENTI = "north imenti"
    NORTH_MUGIRANGO = "north mugirango"
    NYAKACH = "nyakach"
    NYALI = "nyali"
    NYANDO = "nyando"
    NYARIBARI_CHACHE = "nyaribari chache"
    NYARIBARI_MASABA = "nyaribari masaba"
    NYATIKE = "nyatike"
    NYERI_TOWN = "nyeri town"
    OL_JOROK = "ol jorok"
    OL_KALOU = "ol kalou"
    OTHAYA = "othaya"
    POKOT_SOUTH = "pokot south"
    RABAI = "rabai"
    RANGWE = "rangwe"
    RARIEDA = "rarieda"
    RONGAI = "rongai"
    RONGO = "rongo"
    ROYSAMBU = "roysambu"
    RUARAKA = "ruaraka"
    RUIRU = "ruiru"
    RUNYENJES = "runyenjes"
    SABATIA = "sabatia"
    SABOTI = "saboti"
    SAKU = "saku"
    SAMBURU_EAST = "samburu east"
    SAMBURU_NORTH = "samburu north"
    SAMBURU_WEST = "samburu west"
    SEME = "seme"
    SHINYALU = "shinyalu"
    SIGOR = "sigor"
    SIGOWET_SOIN = "sigowet/soin"
    SIRISIA = "sirisia"
    SOTIK = "sotik"
    SOUTH_IMENTI = "south imenti"
    SOUTH_MUGIRANGO = "south mugirango"
    SOY = "soy"
    STAREHE = "starehe"
    SUBA_NORTH_MBITA = "suba north/mbita"
    SUBA_SOUTH = "suba south"
    SUBUKIA = "subukia"
    SUNA_EAST = "suna east"
    SUNA_WEST = "suna west"
    TARBAJ = "tarbaj"
    TAVETA = "taveta"
    TESO_NORTH = "teso north"
    TESO_SOUTH = "teso south"
    TETU = "tetu"
    THARAKA = "tharaka"
    THIKA_TOWN = "thika town"
    TIATY = "tiaty"
    TIGANIA_EAST = "tigania east"
    TIGANIA_WEST = "tigania west"
    TINDERET = "tinderet"
    TONGAREN = "tongaren"
    TURBO = "turbo"
    TURKANA_CENTRAL = "turkana central"
    TURKANA_EAST = "turkana east"
    TURKANA_NORTH = "turkana north"
    TURKANA_SOUTH = "turkana south"
    TURKANA_WEST = "turkana west"
    UGENYA = "ugenya"
    UGUNJA = "ugunja"
    URIRI = "uriri"
    VIHIGA = "vihiga"  # (Shadows county name "vihiga")
    VOI = "voi"
    WAJIR_EAST = "wajir east"
    WAJIR_NORTH = "wajir north"
    WAJIR_SOUTH = "wajir south"
    WAJIR_WEST = "wajir west"
    WEBUYE_EAST = "webuye east"
    WEBUYE_WEST = "webuye west"
    WESTLANDS = "westlands"
    WEST_MUGIRANGO = "west mugirango"
    WUNDANYI = "wundanyi"
    YATTA = "yatta"

    # Kenya Wards
    ABAKAILE = "abakaile"
    ABOGETA_EAST = "abogeta east"
    ABOGETA_WEST = "abogeta west"
    ABOTHUGUCHI_CENTRAL = "abothuguchi central"
    ABOTHUGUCHI_WEST = "abothuguchi west"
    ADAMASAJIDE = "adamasajide"
    ADU = "adu"
    AGENG_A_NANGUBA = "ageng'a nanguba"
    AGUTHI_GAAKI = "aguthi-gaaki"
    AHERO = "ahero"
    AINABKOI_OLARE = "ainabkoi/olare"
    AINAMOI = "ainamoi"
    AIRBASE = "airbase"
    AIRPORT = "airport"
    AKACHIU = "akachiu"
    AKIRANG_ONDU = "akirang'ondu"
    AKITHII = "akithii"
    ALALE = "alale"
    ALANGO_GOF = "alango gof"
    AMALO = "amalo"
    AMUKURA_CENTRAL = "amukura central"
    AMUKURA_EAST = "amukura east"
    AMUKURA_WEST = "amukura west"
    AMWATHI = "amwathi"
    ANGATA_BARIKOI = "angata barikoi"
    ANGATA_NANYOKIE = "angata nanyokie"
    ANG_OROM = "ang'orom"
    ANG_URAI_EAST = "ang'urai east"
    ANG_URAI_NORTH = "ang'urai north"
    ANG_URAI_SOUTH = "ang'urai south"
    ANTUAMBUI = "antuambui"
    ANTUBETWE_KIONGO = "antubetwe kiongo"
    ARABIA = "arabia"
    ARBAJAHAN = "arbajahan"
    ARROR = "arror"
    ASHABITO = "ashabito"
    ATHI = "athi"
    ATHIRU_GAITI = "athiru gaiti"
    ATHIRU_RUUJINE = "athiru ruujine"
    ATHI_RIVER = "athi river"
    ATHWANA = "athwana"
    AWASI_ONJIKO = "awasi/onjiko"
    BAAWA = "baawa"
    BABA_DOGO = "baba dogo"
    BAHARI = "bahari"
    BAHATI = "bahati"
    BALAMBALA = "balambala"
    BAMBA = "bamba"
    BAMBURI = "bamburi"
    BANGALE = "bangale"
    BANISSA = "banissa"
    BANJA = "banja"
    BARAGWI = "baragwi"
    BARAKI = "baraki"
    BARTABWA = "bartabwa"
    BARUT = "barut"
    BARWAGO = "barwago"
    BARWESSA = "barwessa"
    BASI_BOGETAORIO = "basi bogetaorio"
    BASI_CENTRAL = "basi central"
    BASUBA = "basuba"
    BATALU = "batalu"
    BATEI = "batei"
    BENANE_LAGDERA = "benane-lagdera"
    BENANE_WAJIR_SOUTH = "benane-wajir south"
    BIASHARA_NAIVASHA = "biashara-naivasha"
    BIASHARA_NAKURU_TOWN_EAST = "biashara-nakuru town east"
    BIASHARA_RUIRU = "biashara-ruiru"
    BIBIRIONI = "bibirioni"
    BIDII = "bidii"
    BIRONGO = "birongo"
    BOBARACHO = "bobaracho"
    BOBASI_BOITANGARE = "bobasi boitangare"
    BOBASI_CHACHE = "bobasi chache"
    BOFU = "bofu"
    BOGEKA = "bogeka"
    BOGETENGA = "bogetenga"
    BOGIAKUMU = "bogiakumu"
    BOGICHORA = "bogichora"
    BOGUSERO = "bogusero"
    BOIKANG_A = "boikang'a"
    BOITO = "boito"
    BOKEIRA = "bokeira"
    BOKIMONGE = "bokimonge"
    BOKOLI = "bokoli"
    BOMANI = "bomani"
    BOMARIBA = "bomariba"
    BOMBABA_BORABU = "bombaba borabu"
    BOMORENDA = "bomorenda"
    BOMWAGAMO = "bomwagamo"
    BONYAMATUTA = "bonyamatuta"
    BOOCHI_BORABU = "boochi borabu"
    BOOCHI_TENDERE = "boochi/tendere"
    BORABU_CHITAGO = "borabu/chitago"
    BOSAMARO = "bosamaro"
    BOSOTI_SENGERA = "bosoti/sengera"
    BUKEMBE_EAST = "bukembe east"
    BUKEMBE_WEST = "bukembe west"
    BUKHAYO_CENTRAL = "bukhayo central"
    BUKHAYO_EAST = "bukhayo east"
    BUKHAYO_NORTH_WALTSI = "bukhayo north/waltsi"
    BUKHAYO_WEST = "bukhayo west"
    BUKIRA_CENTRL_IKEREGE = "bukira centrl/ikerege"
    BUKIRA_EAST = "bukira east"
    BULLA_PESA = "bulla pesa"
    BUMULA = "bumula"
    BUNYALA_CENTRAL_BUDALANGI = "bunyala central"
    BUNYALA_CENTRAL_NAVAKHOLO = "bunyala central"
    BUNYALA_EAST = "bunyala east"
    BUNYALA_NORTH = "bunyala north"
    BUNYALA_SOUTH = "bunyala south"
    BUNYALA_WEST_BUDALANGI = "bunyala west"
    BUNYALA_WEST_NAVAKHOLO = "bunyala west"
    BURAT = "burat"
    BURA_FAFI = "bura-fafi"
    BURA_MWATATE = "bura-mwatate"
    BURDER = "burder"
    BURUMBA = "burumba"
    BUSALI = "busali"
    BUSIBWABO = "busibwabo"
    BUTALI_CHEGULO = "butali/chegulo"
    BUTE = "bute"
    BUTIYE = "butiye"
    BUTSOTSO_CENTRAL = "butsotso central"
    BUTSOTSO_EAST = "butsotso east"
    BUTSOTSO_SOUTH = "butsotso south"
    BWAKE_LUUYA = "bwake/luuya"
    BWIRI = "bwiri"
    CALIFORNIA = "california"
    CENTRAL_ALEGO = "central alego"
    CENTRAL_BUNYORE = "central bunyore"
    CENTRAL_GEM = "central gem"
    CENTRAL_KAMAGAMBO = "central kamagambo"
    CENTRAL_KANYAMKAGO = "central kanyamkago"
    CENTRAL_KARACHUONYO = "central-karachuonyo"
    CENTRAL_KASIPUL = "central kasipul"
    CENTRAL_KISUMU = "central kisumu"
    CENTRAL_MARAGOLI = "central maragoli"
    CENTRAL_MWINGI_CENTRAL = "central-mwingi central"
    CENTRAL_NDARAGWA = "central-ndaragwa"
    CENTRAL_NYAKACH = "central nyakach"
    CENTRAL_SAKWA_AWENDO = "central sakwa"
    CENTRAL_SAKWA_BONDO = "central sakwa"
    CENTRAL_SEME = "central seme"
    CENTRAL_WARD = "central ward"
    CHAANI = "chaani"
    CHAIK = "chaik"
    CHAKOL_NORTH = "chakol north"
    CHAKOL_SOUTH = "chakol south"
    CHALA = "chala"
    CHANGAMWE = "changamwe"
    CHANIA = "chania"
    CHARAGITA = "charagita"
    CHARI = "chari"
    CHASIMBA = "chasimba"
    CHAVAKALI = "chavakali"
    CHAWIA = "chawia"
    CHEBOIN = "cheboin"
    CHEBUNYO = "chebunyo"
    CHEKALINI = "chekalini"
    CHEMAGEL = "chemagel"
    CHEMANER = "chemaner"
    CHEMELIL = "chemelil"
    CHEMELIL_CHEMASE = "chemelil/chemase"
    CHEMOSOT = "chemosot"
    CHEMUCHE = "chemuche"
    CHEMUNDU_KAPNG_ETUNY = "chemundu/kapng'etuny"
    CHENGONI_SAMBURU = "chengoni/samburu"
    CHEPARERIA = "chepareria"
    CHEPCHABAS = "chepchabas"
    CHEPCHOINA = "chepchoina"
    CHEPKORIO = "chepkorio"
    CHEPKUMIA = "chepkumia"
    CHEPKUNYUK = "chepkunyuk"
    CHEPLANGET = "cheplanget"
    CHEPSEON = "chepseon"
    CHEPSIRO_KIPTOROR = "chepsiro/kiptoror"
    CHEPTAIS = "cheptais"
    CHEPTERWAI = "chepterwai"
    CHEPTIRET_KIPCHAMO = "cheptiret/kipchamo"
    CHEPTORORIET_SERETUT = "cheptororiet/seretut"
    CHEPYUK = "chepyuk"
    CHERAB = "cherab"
    CHERANGANY_SUWERWA = "cherangany/suwerwa"
    CHERANG_ANY_CHEBORORWA = "cherang'any/chebororwa"
    CHESIKAKI = "chesikaki"
    CHESOEN = "chesoen"
    CHEVAYWA = "chevaywa"
    CHEWANI = "chewani"
    CHEWELE = "chewele"
    CHIAKARIGA = "chiakariga"
    CHILCHILA = "chilchila"
    CHINGA = "chinga"
    CHOGORIA = "chogoria"
    CHULUNI = "chuluni"
    CHURO_AMAYA = "churo/amaya"
    CIANDA = "cianda"
    CLAY_CITY = "clay city"
    DABASO = "dabaso"
    DADAAB = "dadaab"
    DADAJA_BULLA = "dadaja bulla"
    DALALEKUTUK = "dalalekutuk"
    DAMAJALE = "damajale"
    DANABA = "danaba"
    DANDORA_AREA_I = "dandora area i"
    DANDORA_AREA_II = "dandora area ii"
    DANDORA_AREA_III = "dandora area iii"
    DANDORA_AREA_IV = "dandora area iv"
    DANDU = "dandu"
    DANYERE = "danyere"
    DEDAN_KIMANTHI = "dedan kimanthi"
    DEKAHARIA = "dekaharia"
    DELLA = "della"
    DERKHALE = "derkhale"
    DERTU = "dertu"
    DIIF = "diif"
    DUKANA = "dukana"
    DUNDORI = "dundori"
    DZOMBO = "dzombo"
    EASTLEIGH_NORTH = "eastleigh north"
    EASTLEIGH_SOUTH = "eastleigh south"
    EAST_ASEMBO = "east asembo"
    EAST_GEM_GEM = "east gem"
    EAST_GEM_RANGWE = "east gem"
    EAST_KABRAS = "east kabras"
    EAST_KAMAGAK = "east kamagak"
    EAST_KAMAGAMBO = "east kamagambo"
    EAST_KANO_WAWIDHI = "east kano/wawidhi"
    EAST_KANYAMKAGO = "east kanyamkago"
    EAST_SANG_ALO = "east sang'alo"
    EAST_SEME = "east seme"
    EAST_UGENYA = "east ugenya"
    EAST_WANGA = "east wanga"
    EKALAKALA = "ekalakala"
    EKERENYO = "ekerenyo"
    ELBEN = "elben"
    ELBURGON = "elburgon"
    ELDAS = "eldas"
    ELEMENTAITA = "elementaita"
    ELGON = "elgon"
    ELNUR_TULA_TULA = "elnur/tula tula"
    ELUGULU = "elugulu"
    ELWAK_NORTH = "elwak north"
    ELWAK_SOUTH = "elwak south"
    EL_BARTA = "el-barta"
    EMABUNGO = "emabungo"
    EMALI_MULALA = "emali/mulala"
    EMBAKASI = "embakasi"
    EMBOBUT_EMBULOT = "embobut/embulot"
    EMBOMOS = "embomos"
    EMINING = "emining"
    EMSOO = "emsoo"
    ENDAU_MALALANI = "endau/malalani"
    ENDEBESS = "endebess"
    ENDO = "endo"
    ENDUGH = "endugh"
    ENGINEER = "engineer"
    ENTONET_LENKISIM = "entonet/lenkisim"
    ESISE = "esise"
    ETENJE = "etenje"
    EVURORE = "evurore"
    EWALEL_CHAPCHAP = "ewalel/chapchap"
    EWUASO_OONKIDONG_I = "ewuaso oonkidong'i"
    FAFI = "fafi"
    FAZA = "faza"
    FINO = "fino"
    FLAMINGO = "flamingo"
    FRERE_TOWN = "frere town"
    GACHUBA = "gachuba"
    GAICHANJIRU = "gaichanjiru"
    GAKAWA = "gakawa"
    GALBET = "galbet"
    GANDA = "ganda"
    GANGA = "ganga"
    GANYURE_WAGALLA = "ganyure/wagalla"
    GANZE = "ganze"
    GARASHI = "garashi"
    GARBATULLA = "garbatulla"
    GARSEN_CENTRAL = "garsen central"
    GARSEN_NORTH = "garsen north"
    GARSEN_SOUTH = "garsen south"
    GARSEN_WEST = "garsen west"
    GATANGA = "gatanga"
    GATARAKWA = "gatarakwa"
    GATHANJI = "gathanji"
    GATHARA = "gathara"
    GATHIGIRIRI = "gathigiriri"
    GATIMU = "gatimu"
    GATINA = "gatina"
    GATITU_MURUGURU = "gatitu/muruguru"
    GATONGORA = "gatongora"
    GATUANYAGA = "gatuanyaga"
    GATUNGA = "gatunga"
    GATURI = "gaturi"
    GATURI_NORTH = "gaturi north"
    GATURI_SOUTH = "gaturi south"
    GEMBE = "gembe"
    GESIMA = "gesima"
    GESUSU = "gesusu"
    GETA = "geta"
    GETENGA = "getenga"
    GIKONDI = "gikondi"
    GILGIL = "gilgil"
    GISAMBAI = "gisambai"
    GITARU = "gitaru"
    GITHABAI = "githabai"
    GITHER = "gither"
    GITHIGA_GITHUNGURI = "githiga-githunguri"
    GITHIGA_LAIKIPIA_WEST = "githiga-laikipia west"
    GITHIORO = "githioro"
    GITHOBOKONI = "githobokoni"
    GITHUNGURI = "githunguri"
    GITHURAI = "githurai"
    GITOTHUA = "gitothua"
    GITUAMBA = "gituamba"
    GITUGI = "gitugi"
    GODOMA = "godoma"
    GOD_JOPE = "god jope"
    GOKEHARAKA_GETAMBWEGA = "gokeharaka/getambwega"
    GOLBO = "golbo"
    GOMBATO_BONGWE = "gombato bongwe"
    GONGONI = "gongoni"
    GOREALE = "goreale"
    GOT_KACHOLA = "got kachola"
    GUBA = "guba"
    GURAR = "gurar"
    GUTICHA = "guticha"
    GWASSI_NORTH = "gwassi north"
    GWASSI_SOUTH = "gwassi south"
    HABASSWEIN = "habasswein"
    HADADO_ATHIBOHOL = "hadado/athibohol"
    HARAMBEE = "harambee"
    HEILLU_MANYATTA = "heillu/manyatta"
    HELLS_GATE = "hells gate"
    HINDI = "hindi"
    HIRIMANI = "hirimani"
    HOMA_BAY_ARUJO = "homa bay arujo"
    HOMA_BAY_CENTRAL = "homa bay central"
    HOMA_BAY_EAST = "homa bay east"
    HOMA_BAY_WEST = "homa bay west"
    HONGWE = "hongwe"
    HOSPITAL_KIMININI = "hospital-kiminini"
    HOSPITAL_MATHARE = "hospital-mathare"
    HOSPITAL_THIKA_TOWN = "hospital-thika town"
    HULUGHO = "hulugho"
    HURUMA_MATHARE = "huruma-mathare"
    HURUMA_TURBO = "huruma-turbo"
    IBENO = "ibeno"
    IBRAHIM_URE = "ibrahim ure"
    ICHAGAKI = "ichagaki"
    ICHUNI = "ichuni"
    IDAKHO_CENTRAL = "idakho central"
    IDAKHO_EAST = "idakho east"
    IDAKHO_NORTH = "idakho north"
    IDAKHO_SOUTH = "idakho south"
    IFTIN = "iftin"
    IGAMBANG_OMBE = "igambang'ombe"
    IGEMBE_EAST = "igembe east"
    IGOJI_EAST = "igoji east"
    IGOJI_WEST = "igoji west"
    IGWAMITI = "igwamiti"
    IJARA = "ijara"
    IKANGA_KYATUNE = "ikanga/kyatune"
    IKINU = "ikinu"
    IKOMBE = "ikombe"
    IKUTHA = "ikutha"
    ILCHAMUS = "ilchamus"
    ILDAMAT_KAJIADO_CENTRAL = "ildamat-kajiado central"
    ILDAMAT_NAROK_EAST = "ildamat-narok east"
    ILIMA = "ilima"
    ILKERIN = "ilkerin"
    ILLERET = "illeret"
    ILMOTIOK = "ilmotiok"
    ILOODOKILANI = "iloodokilani"
    IMARA_DAIMA = "imara daima"
    IMARORO = "imaroro"
    INGOSTSE_MATHIA = "ingostse-mathia"
    INOI = "inoi"
    IRIAINI = "iriaini"
    IRIA_INI = "iria-ini"
    ISIBANIA = "isibania"
    ISUKHA_CENTRAL = "isukha central"
    ISUKHA_EAST = "isukha east"
    ISUKHA_NORTH = "isukha north"
    ISUKHA_SOUTH = "isukha south"
    ISUKHA_WEST = "isukha west"
    ITHANGA = "ithanga"
    ITHIRU = "ithiru"
    ITIBO = "itibo"
    IVINGONI_NZAMBANI = "ivingoni/nzambani"
    JARAJILA = "jarajila"
    JARA_JARA = "jara jara"
    JARIBUNI = "jaribuni"
    JEPKOYAI = "jepkoyai"
    JILORE = "jilore"
    JOMVU_KUU = "jomvu kuu"
    JUJA = "juja"
    JUNDA = "junda"
    JUNJU = "junju"
    KAALENG_KAIKOR = "kaaleng/kaikor"
    KABARE = "kabare"
    KABARNET = "kabarnet"
    KABARTONJO = "kabartonjo"
    KABARU = "kabaru"
    KABATINI = "kabatini"
    KABAZI = "kabazi"
    KABETE = "kabete"
    KABIANGA = "kabianga"
    KABIEMIT = "kabiemit"
    KABIRO = "kabiro"
    KABISAGA = "kabisaga"
    KABIYET = "kabiyet"
    KABONDO_EAST = "kabondo east"
    KABONDO_WEST = "kabondo west"
    KABONYO_KANYAGWAL = "kabonyo/kanyagwal"
    KABUCHAI_CHWELE = "kabuchai/chwele"
    KABULA = "kabula"
    KABUOCH_NORTH = "kabuoch north"
    KABUOCH_SOUTH_PALA = "kabuoch south/pala"
    KABWARENG = "kabwareng"
    KACHIEN_G = "kachien'g"
    KADZANDANI = "kadzandani"
    KAERIS = "kaeris"
    KAGAARI_NORTH = "kagaari north"
    KAGAARI_SOUTH = "kagaari south"
    KAGAN = "kagan"
    KAGUNDU_INI = "kagundu-ini"
    KAHAWA = "kahawa"
    KAHAWA_SUKARI = "kahawa sukari"
    KAHAWA_WENDANI = "kahawa wendani"
    KAHAWA_WEST = "kahawa west"
    KAHUMBU = "kahumbu"
    KAIMBAGA = "kaimbaga"
    KAJULU = "kajulu"
    KAKRAO = "kakrao"
    KAKSINGRI_WEST = "kaksingri west"
    KAKUMA = "kakuma"
    KAKUYUNI = "kakuyuni"
    KAKUZI_MITUBIRI = "kakuzi/mitubiri"
    KALAMA = "kalama"
    KALAPATA = "kalapata"
    KALAWA = "kalawa"
    KALER = "kaler"
    KALIMONI = "kalimoni"
    KALOBEYEI = "kalobeyei"
    KALOKOL = "kalokol"
    KALOLENI_KALOLENI = "kaloleni-kaloleni"
    KALOLENI_VOI = "kaloleni-voi"
    KAMACHARIA = "kamacharia"
    KAMAGUT = "kamagut"
    KAMAHUHA = "kamahuha"
    KAMAKWA_MUKARO = "kamakwa/mukaro"
    KAMARA = "kamara"
    KAMARINY = "kamariny"
    KAMASIAN = "kamasian"
    KAMBE_RIBE = "kambe/ribe"
    KAMBITI = "kambiti"
    KAMBURU = "kamburu"
    KAMENU = "kamenu"
    KAMUKUYWA = "kamukuywa"
    KANAMKEMER = "kanamkemer"
    KANGAI = "kangai"
    KANGARI = "kangari"
    KANGEMI = "kangemi"
    KANGETA = "kangeta"
    KANGUNDO_CENTRAL = "kangundo central"
    KANGUNDO_EAST = "kangundo east"
    KANGUNDO_NORTH = "kangundo north"
    KANGUNDO_WEST = "kangundo west"
    KANG_ATOTHA = "kang'atotha"
    KANJUIRI_RANGE = "kanjuiri range"
    KANUNI = "kanuni"
    KANYADOTO = "kanyadoto"
    KANYALUO = "kanyaluo"
    KANYAMWA_KOLOGI = "kanyamwa kologi"
    KANYAMWA_KOSEWE = "kanyamwa kosewe"
    KANYANGI = "kanyangi"
    KANYASA = "kanyasa"
    KANYEKINI = "kanyekini"
    KANYENYA_INI = "kanyenya-ini"
    KANYIKELA = "kanyikela"
    KANZIKO = "kanziko"
    KAPCHEMUTWA = "kapchemutwa"
    KAPCHOK = "kapchok"
    KAPCHORUA = "kapchorua"
    KAPEDO_NAPEITOM = "kapedo/napeitom"
    KAPENGURIA = "kapenguria"
    KAPKANGANI = "kapkangani"
    KAPKATENY = "kapkateny"
    KAPKATET = "kapkatet"
    KAPKUGERWET = "kapkugerwet"
    KAPKURES_NAKURU_TOWN_WEST = "kapkures-nakuru town west"
    KAPKURES_SOY = "kapkures-soy"
    KAPLAMAI = "kaplamai"
    KAPLELARTET = "kaplelartet"
    KAPLETUNDO = "kapletundo"
    KAPOMBOI = "kapomboi"
    KAPROPITA = "kapropita"
    KAPSABET = "kapsabet"
    KAPSAOS_AINAMOI = "kapsaos-ainamoi"
    KAPSAOS_TURBO = "kapsaos-turbo"
    KAPSASIAN = "kapsasian"
    KAPSIMOTWO = "kapsimotwo"
    KAPSOIT = "kapsoit"
    KAPSOWAR = "kapsowar"
    KAPSOYA = "kapsoya"
    KAPSUSER = "kapsuser"
    KAPTAGAT = "kaptagat"
    KAPTAMA = "kaptama"
    KAPTARAKWA = "kaptarakwa"
    KAPTEL_KAMOIYWO = "kaptel/kamoiywo"
    KAPTEMBWO = "kaptembwo"
    KAPTUMO_KABOI = "kaptumo-kaboi"
    KAPUTIEI_NORTH = "kaputiei north"
    KAPUTIR = "kaputir"
    KAPYEGO = "kapyego"
    KARAI = "karai"
    KARAMA = "karama"
    KARARE = "karare"
    KARATINA_TOWN = "karatina town"
    KARAU = "karau"
    KAREN = "karen"
    KARGI_SOUTH_HORR = "kargi/south horr"
    KARIARA = "kariara"
    KARIMA = "karima"
    KARINGANI = "karingani"
    KARIOBANGI_NORTH = "kariobangi north"
    KARIOBANGI_SOUTH = "kariobangi south"
    KARITI = "kariti"
    KARUMANDI = "karumandi"
    KARUNA_MEIBEKI = "karuna/meibeki"
    KARURA = "karura"
    KARURI = "karuri"
    KASARANI = "kasarani"
    KASEI = "kasei"
    KASEMENI = "kasemeni"
    KASGUNGA = "kasgunga"
    KASIGAU = "kasigau"
    KASIKEU = "kasikeu"
    KATANGI = "katangi"
    KATHIANI_CENTRAL = "kathiani central"
    KATHONZWENI = "kathonzweni"
    KATILIA = "katilia"
    KATILU = "katilu"
    KAUWI = "kauwi"
    KAWANGWARE = "kawangware"
    KAYAFUNGO = "kayafungo"
    KAYOLE_CENTRAL = "kayole central"
    KAYOLE_NORTH = "kayole north"
    KAYOLE_SOUTH = "kayole south"
    KEDOWA_KIMUGUL = "kedowa/kimugul"
    KEE = "kee"
    KEEKONYOKIE_KAJIADO_WEST = "keekonyokie-kajiado west"
    KEEKONYOKIE_NAROK_EAST = "keekonyokie-narok east"
    KEGOGI = "kegogi"
    KEIYO = "keiyo"
    KEMBU = "kembu"
    KEMELOI_MARABA = "kemeloi-maraba"
    KEMERA = "kemera"
    KENDU_BAY_TOWN = "kendu bay town"
    KENYAWA_POKA = "kenyawa-poka"
    KERINGET = "keringet"
    KERIO_DELTA = "kerio delta"
    KERUGOYA = "kerugoya"
    KEUMBU = "keumbu"
    KEYIAN = "keyian"
    KHALABA_KANDUYI = "khalaba-kanduyi"
    KHALABA_MATUNGU = "khalaba-matungu"
    KHALALIO = "khalalio"
    KHASOKO = "khasoko"
    KHOLERA = "kholera"
    KHOROF_HARAR = "khorof/harar"
    KIABONYORU = "kiabonyoru"
    KIAGU = "kiagu"
    KIAMAIKO = "kiamaiko"
    KIAMAINA = "kiamaina"
    KIAMBERE = "kiambere"
    KIAMOKAMA = "kiamokama"
    KIAMWANGI = "kiamwangi"
    KIANJAI = "kianjai"
    KIBARANI = "kibarani"
    KIBAUNI = "kibauni"
    KIBINGEI = "kibingei"
    KIBIRI = "kibiri"
    KIBIRICHIA = "kibirichia"
    KIBISH = "kibish"
    KIEGOI_ANTUBOCHIU = "kiegoi/antubochiu"
    KIGANJO = "kiganjo"
    KIGANJO_MATHARI = "kiganjo/mathari"
    KIGUCHWA = "kiguchwa"
    KIGUMO = "kigumo"
    KIHARA = "kihara"
    KIHINGO = "kihingo"
    KIHUMBU_INI = "kihumbu-ini"
    KIIMA_KIU_KALANZONI = "kiima kiu/kalanzoni"
    KIINE = "kiine"
    KIIRUA_NAARI = "kiirua/naari"
    KIJABE = "kijabe"
    KIKUMBULYU_NORTH = "kikumbulyu north"
    KIKUMBULYU_SOUTH = "kikumbulyu south"
    KIKUYU = "kikuyu"
    KILELESHWA = "kileleshwa"
    KILGORIS_CENTRAL = "kilgoris central"
    KILIBWONI = "kilibwoni"
    KILIMANI = "kilimani"
    KILIWEHIRI = "kiliwehiri"
    KILUNGU = "kilungu"
    KIMAETI = "kimaeti"
    KIMANA = "kimana"
    KIMILILI = "kimilili"
    KIMININI = "kiminini"
    KIMINTET = "kimintet"
    KIMORORI_WEMPA = "kimorori/wempa"
    KIMULOT = "kimulot"
    KIMUMU = "kimumu"
    KINAKOMBA = "kinakomba"
    KINALE = "kinale"
    KINANGO = "kinango"
    KINANIE = "kinanie"
    KINGANDOLE = "kingandole"
    KINNA = "kinna"
    KINONDO = "kinondo"
    KINOO = "kinoo"
    KINYONA = "kinyona"
    KINYORO = "kinyoro"
    KIOGORO = "kiogoro"
    KIOMO_KYETHANI = "kiomo/kyethani"
    KIPCHEBOR = "kipchebor"
    KIPCHIMCHIM = "kipchimchim"
    KIPEVU = "kipevu"
    KIPINI_EAST = "kipini east"
    KIPINI_WEST = "kipini west"
    KIPIPIRI = "kipipiri"
    KIPKAREN = "kipkaren"
    KIPKELION = "kipkelion"
    KIPKENYO = "kipkenyo"
    KIPLOMBE = "kiplombe"
    KIPRERES = "kipreres"
    KIPSOMBA = "kipsomba"
    KIPSONOI = "kipsonoi"
    KIPTAGICH = "kiptagich"
    KIPTORORO = "kiptororo"
    KIPTUYA = "kiptuya"
    KIRIITA = "kiriita"
    KIRIMARI = "kirimari"
    KIRIMUKUYU = "kirimukuyu"
    KIRU = "kiru"
    KISANANA = "kisanana"
    KISASI = "kisasi"
    KISA_CENTRAL = "kisa central"
    KISA_EAST = "kisa east"
    KISA_NORTH = "kisa north"
    KISA_WEST = "kisa west"
    KISIARA = "kisiara"
    KISII_CENTRAL = "kisii central"
    KISIMA = "kisima"
    KISUMU_NORTH = "kisumu north"
    KITENGELA = "kitengela"
    KITETA_KISAU = "kiteta/kisau"
    KITHIMANI = "kithimani"
    KITHIMU = "kithimu"
    KITHUNGO_KITUNDU = "kithungo/kitundu"
    KITISE_KITHUKI = "kitise/kithuki"
    KITISURU = "kitisuru"
    KITUTU_CENTRAL = "kitutu central"
    KIUNGA = "kiunga"
    KIUU = "kiuu"
    KIVAA = "kivaa"
    KIVOU = "kivou"
    KIVUMBINI = "kivumbini"
    KIWAWA = "kiwawa"
    KOBUJOI = "kobujoi"
    KOBURA = "kobura"
    KOCHIA = "kochia"
    KODICH = "kodich"
    KOIBATEK = "koibatek"
    KOJWACH = "kojwach"
    KOKWANYO_KAKELO = "kokwanyo/kakelo"
    KOLA = "kola"
    KOLOWA = "kolowa"
    KOLWA_CENTRAL = "kolwa central"
    KOLWA_EAST = "kolwa east"
    KOMAROCK = "komarock"
    KOMOTHAI = "komothai"
    KONDELE = "kondele"
    KONGONI = "kongoni"
    KONGOWEA = "kongowea"
    KONG_ASIS = "kong'asis"
    KONYU = "konyu"
    KOROGOCHO = "korogocho"
    KORONDILE = "korondile"
    KORR_NGURUNIT = "korr/ngurunit"
    KOSIRAI = "kosirai"
    KOTARUK_LOBEI = "kotaruk/lobei"
    KOYONZO = "koyonzo"
    KOYO_NDURIO = "koyo-ndurio"
    KUBO_SOUTH = "kubo south"
    KUINET_KAPSUSWA = "kuinet/kapsuswa"
    KUKU = "kuku"
    KUNYAK = "kunyak"
    KURGUNG_SURUNGAI = "kurgung/surungai"
    KUTULO = "kutulo"
    KWA = "kwa"
    KWABWAI = "kwabwai"
    KWANZA = "kwanza"
    KWARE = "kware"
    KWAVONZA_YATTA = "kwavonza/yatta"
    KWA_MUTONGA_KITHUMULA = "kwa mutonga/kithumula"
    KWA_NJENGA = "kwa njenga"
    KWA_REUBEN = "kwa reuben"
    KYANGWITHYA_EAST = "kyangwithya east"
    KYANGWITHYA_WEST = "kyangwithya west"
    KYELENI = "kyeleni"
    KYENI_NORTH = "kyeni north"
    KYENI_SOUTH = "kyeni south"
    KYOME_THAANA = "kyome/thaana"
    KYUSO = "kyuso"
    LABASIGALE = "labasigale"
    LAFEY = "lafey"
    LAGBOGHOL_SOUTH = "lagboghol south"
    LAGSURE = "lagsure"
    LAINI_SABA = "laini saba"
    LAISAMIS = "laisamis"
    LAKE_VIEW = "lake view"
    LAKE_ZONE = "lake zone"
    LAKOLEY_SOUTH_BASIR = "lakoley south/basir"
    LAMBWE = "lambwe"
    LANDIMAWE = "landimawe"
    LANET_UMOJA = "lanet/umoja"
    LANGAS = "langas"
    LAPUR = "lapur"
    LARE = "lare"
    LARI_KIRENGA = "lari/kirenga"
    LELAN_MARAKWET_WEST = "lelan-marakwet west"
    LELAN_POKOT_SOUTH = "lelan-pokot south"
    LELMOKWO_NGECHEK = "lelmokwo/ngechek"
    LEMBUS = "lembus"
    LEMBUS_KWEN = "lembus kwen"
    LEMBUS_PERKERRA = "lembus/perkerra"
    LESHAU_PONDO = "leshau/pondo"
    LETEA = "letea"
    LIBEHIA = "libehia"
    LIBOI = "liboi"
    LIKONI = "likoni"
    LIKUYANI = "likuyani"
    LIMURU_CENTRAL = "limuru central"
    LIMURU_EAST = "limuru east"
    LINDI = "lindi"
    LITEIN = "litein"
    LOBOKAT = "lobokat"
    LODOKEJEK = "lodokejek"
    LODWAR_TOWNSHIP = "lodwar township"
    LOGO_LOGO = "logo logo"
    LOIMA = "loima"
    LOITA = "loita"
    LOIYAMOROCK = "loiyamorock"
    LOIYANGALANI = "loiyangalani"
    LOKICHAR = "lokichar"
    LOKICHOGGIO = "lokichoggio"
    LOKIRIAMA_LORENGIPPI = "lokiriama/lorengippi"
    LOKORI_KOCHODIN = "lokori/kochodin"
    LOLGORIAN = "lolgorian"
    LOMUT = "lomut"
    LONDIANI = "londiani"
    LONDON = "london"
    LONGISA = "longisa"
    LOOSUK = "loosuk"
    LOPUR = "lopur"
    LOWER_KAEWA_KAANI = "lower kaewa/kaani"
    LOWER_SAVANNAH = "lower savannah"
    LUANDA_SOUTH = "luanda south"
    LUANDA_TOWNSHIP = "luanda township"
    LUCKY_SUMMER = "lucky summer"
    LUGAGA_WAMULUMA = "lugaga-wamuluma"
    LUGARI = "lugari"
    LUMAKANDA = "lumakanda"
    LUSHEYA_LUBINU = "lusheya/lubinu"
    LWANDANYI = "lwandanyi"
    LWANDETI = "lwandeti"
    LYADUYWA_IZAVA = "lyaduywa/izava"
    MAALIMIN = "maalimin"
    MABATINI = "mabatini"
    MACALDER_KANYARWANDA = "macalder/kanyarwanda"
    MACHAKOS_CENTRAL = "machakos central"
    MACHEWA = "machewa"
    MACKINNON_ROAD = "mackinnon road"
    MADOGO = "madogo"
    MAENI = "maeni"
    MAGADI = "magadi"
    MAGARINI = "magarini"
    MAGENCHE = "magenche"
    MAGOGONI = "magogoni"
    MAGOMBO = "magombo"
    MAGUMONI = "magumoni"
    MAGUMU = "magumu"
    MAGUTU = "magutu"
    MAGWAGWA = "magwagwa"
    MAHIAKALO = "mahiakalo"
    MAHIGA = "mahiga"
    MAHOO = "mahoo"
    MAIELLA = "maiella"
    MAIKONA = "maikona"
    MAI_MAHIU = "mai mahiu"
    MAJENGO = "majengo"
    MAJIMOTO_NAROOSURA = "majimoto/naroosura"
    MAJOGE_BASI = "majoge basi"
    MAKERERO = "makerero"
    MAKIMA = "makima"
    MAKINA = "makina"
    MAKINDU = "makindu"
    MAKONGENI = "makongeni"
    MAKUTANO = "makutano"
    MAKUTANO_MWALA = "makutano/mwala"
    MAKUYU = "makuyu"
    MALABA_CENTRAL = "malaba central"
    MALABA_NORTH = "malaba north"
    MALABA_SOUTH = "malaba south"
    MALAHA_ISONGO_MAKUNGA = "malaha/isongo/makunga"
    MALAKISI_SOUTH_KULISIRU = "malakisi/south kulisiru"
    MALEWA_WEST = "malewa west"
    MALINDI_TOWN = "malindi town"
    MALKAGUFU = "malkagufu"
    MALKAMARI = "malkamari"
    MANDA_SHIVANGA = "manda-shivanga"
    MANGA = "manga"
    MANG_U = "mang'u"
    MANYATTA_B = "manyatta 'b'"
    MARA = "mara"
    MARACHI_CENTRAL = "marachi central"
    MARACHI_EAST = "marachi east"
    MARACHI_NORTH = "marachi north"
    MARACHI_WEST = "marachi west"
    MARAFA = "marafa"
    MARAKA = "maraka"
    MARAKARU_TUUTI = "marakaru/tuuti"
    MARALAL = "maralal"
    MARAMA_CENTRAL = "marama central"
    MARAMA_NORTH = "marama north"
    MARAMA_SOUTH = "marama south"
    MARAMA_WEST = "marama west"
    MARANI = "marani"
    MARENYO_SHIANDA = "marenyo-shianda"
    MARIAKANI = "mariakani"
    MARIANI = "mariani"
    MARIASHONI = "mariashoni"
    MARIGAT = "marigat"
    MARIMANTI = "marimanti"
    MARINGO_HAMZA = "maringo/hamza"
    MARKET_MILIMANI = "market milimani"
    MARMANET = "marmanet"
    MARSABIT_CENTRAL = "marsabit central"
    MARUNGU = "marungu"
    MASABA = "masaba"
    MASALANI = "masalani"
    MASIGE_EAST = "masige east"
    MASIGE_WEST = "masige west"
    MASII = "masii"
    MASIMBA = "masimba"
    MASINGA_CENTRAL = "masinga central"
    MASOGO_NYANG_OMA = "masogo/nyang'oma"
    MASONGALENI = "masongaleni"
    MASOOL = "masool"
    MATA = "mata"
    MATAPATO_NORTH = "matapato north"
    MATAPATO_SOUTH = "matapato south"
    MATAYOS_SOUTH = "matayos south"
    MATHARE_NORTH = "mathare north"
    MATINYANI = "matinyani"
    MATISI = "matisi"
    MATOPENI_SPRING_VALLEY = "matopeni/spring valley"
    MATSANGONI = "matsangoni"
    MATULO = "matulo"
    MATUMBEI = "matumbei"
    MATUNGULU_EAST = "matungulu east"
    MATUNGULU_NORTH = "matungulu north"
    MATUNGULU_WEST = "matungulu west"
    MATUU = "matuu"
    MAUA = "maua"
    MAUCHE = "mauche"
    MAUTUMA = "mautuma"
    MAU_NAROK = "mau narok"
    MAVINDINI = "mavindini"
    MAVURIA = "mavuria"
    MAYENJE = "mayenje"
    MAYONI = "mayoni"
    MBAKALO = "mbakalo"
    MBARUK_EBURU = "mbaruk/eburu"
    MBETI_NORTH = "mbeti north"
    MBETI_SOUTH = "mbeti south"
    MBEU = "mbeu"
    MBIRI = "mbiri"
    MBIRIKANI_ESELENKEI = "mbirikani/eselenkei"
    MBITINI_KITUI_RURAL = "mbitini-kitui rural"
    MBITINI_MAKUENI = "mbitini-makueni"
    MBIUNI = "mbiuni"
    MBOGHONI = "mboghoni"
    MBOLOLO = "mbololo"
    MBOONI = "mbooni"
    MEGUN = "megun"
    MEKENENE = "mekenene"
    MELELO = "melelo"
    MELILI = "melili"
    MENENGAI = "menengai"
    MENENGAI_WEST = "menengai west"
    MERIGI = "merigi"
    METKEI = "metkei"
    MFANGANO_ISLAND = "mfangano island"
    MIAMBANI = "miambani"
    MIGOSI = "migosi"
    MIGWANI = "migwani"
    MIHANGO = "mihango"
    MIHUU = "mihuu"
    MIKINDANI = "mikindani"
    MIKINDUNI = "mikinduni"
    MIKINDURI = "mikinduri"
    MILIMA = "milima"
    MIRANGINE = "mirangine"
    MIRITINI = "miritini"
    MISIKHU = "misikhu"
    MITABONI = "mitaboni"
    MITHERU = "mitheru"
    MITUNGUU = "mitunguu"
    MIWANI = "miwani"
    MJAMBERE = "mjambere"
    MJI_WA_KALE_MAKADARA = "mji wa kale/makadara"
    MKOMANI_LAMU_WEST = "mkomani-lamu west"
    MKOMANI_NYALI = "mkomani-nyali"
    MKONGANI = "mkongani"
    MKUNUMBI = "mkunumbi"
    MLANGO_KUBWA = "mlango kubwa"
    MNAGEI = "mnagei"
    MNARANI = "mnarani"
    MOCHONGOI = "mochongoi"
    MODOGASHE = "modogashe"
    MOGOGOSIEK = "mogogosiek"
    MOGONDO = "mogondo"
    MOGOTIO = "mogotio"
    MOIBEN = "moiben"
    MOIBEN_KUSERWO = "moiben/kuserwo"
    MOI_S_BRIDGE = "moi's bridge"
    MOLO = "molo"
    MONYERERO = "monyerero"
    MOROTHILE = "morothile"
    MOSIRO_KAJIADO_WEST = "mosiro-kajiado west"
    MOSIRO_NAROK_EAST = "mosiro-narok east"
    MOSOP = "mosop"
    MOTICHO = "moticho"
    MOTOSIET = "motosiet"
    MOUNTAIN_VIEW = "mountain view"
    MOWLEM = "mowlem"
    MOYALE_TOWNSHIP = "moyale township"
    MTEPENI = "mtepeni"
    MTITO_ANDEI = "mtito andei"
    MTONGWE = "mtongwe"
    MTOPANGA = "mtopanga"
    MUA = "mua"
    MUCHATHA = "muchatha"
    MUGOGODO_EAST = "mugogodo east"
    MUGOGODO_WEST = "mugogodo west"
    MUGOIRI = "mugoiri"
    MUGUGA = "muguga"
    MUGUMO_INI = "mugumo-ini"
    MUGUMU_INI = "mugumu-ini"
    MUGUNDA = "mugunda"
    MUGURU = "muguru"
    MUGWE = "mugwe"
    MUHORONI_KORU = "muhoroni/koru"
    MUHUDU = "muhudu"
    MUHURU = "muhuru"
    MUI = "mui"
    MUKAA = "mukaa"
    MUKOTHIMA = "mukothima"
    MUKURE = "mukure"
    MUKURWE_INI_CENTRAL = "mukurwe-ini central"
    MUKURWE_INI_WEST = "mukurwe-ini west"
    MUKUTANI = "mukutani"
    MUKUYUNI = "mukuyuni"
    MULANGO = "mulango"
    MUMBERES_MAJI_MAZURI = "mumberes/maji mazuri"
    MUMBUNI_NORTH = "mumbuni north"
    MUMIAS_CENTRAL = "mumias central"
    MUMIAS_NORTH = "mumias north"
    MUMINJI = "muminji"
    MUMONI = "mumoni"
    MUNGOMA = "mungoma"
    MUNICIPALITY = "municipality"
    MURARANDIA = "murarandia"
    MURERA = "murera"
    MURHANDA = "murhanda"
    MURINDATI = "murindati"
    MURINDUKO = "murinduko"
    MURUKA = "muruka"
    MURUNGARU = "murungaru"
    MUSANDA = "musanda"
    MUSIKOMA = "musikoma"
    MUTARAKWA = "mutarakwa"
    MUTHA = "mutha"
    MUTHAMBI = "muthambi"
    MUTHARA = "muthara"
    MUTHESYA = "muthesya"
    MUTHETHENI = "muthetheni"
    MUTHITHI = "muthithi"
    MUTHWANI = "muthwani"
    MUTIRA = "mutira"
    MUTITHI = "mutithi"
    MUTITO_KALIKU = "mutito/kaliku"
    MUTITUNI = "mutituni"
    MUTOMO = "mutomo"
    MUTONGUNI = "mutonguni"
    MUTU_INI = "mutu-ini"
    MUVAU_KIKUUMINI = "muvau/kikuumini"
    MUVUTI_KIIMA_KIMWE = "muvuti/kiima-kimwe"
    MWAKIRUNGE = "mwakirunge"
    MWANAMWINGA = "mwanamwinga"
    MWANDA_MGANGE = "mwanda/mgange"
    MWANGANTHIA = "mwanganthia"
    MWARAKAYA = "mwarakaya"
    MWATATE = "mwatate"
    MWAVUMBO = "mwavumbo"
    MWAWESA = "mwawesa"
    MWEA = "mwea"
    MWEIGA = "mweiga"
    MWERENI = "mwereni"
    MWIBONA = "mwibona"
    MWIHOKO = "mwihoko"
    MWIKI_KASARANI = "mwiki-kasarani"
    MWIKI_RUIRU = "mwiki-ruiru"
    MWIMBI = "mwimbi"
    MWIYOGO_ENDARASHA = "mwiyogo/endarasha"
    NAATHU = "naathu"
    NABISWA = "nabiswa"
    NACHOLA = "nachola"
    NACHU = "nachu"
    NAIKARRA = "naikarra"
    NAIROBI_CENTRAL = "nairobi central"
    NAIROBI_SOUTH = "nairobi south"
    NAIROBI_WEST = "nairobi west"
    NAITIRI_KABUYEFWE = "naitiri/kabuyefwe"
    NAIVASHA_EAST = "naivasha east"
    NAKALALE = "nakalale"
    NAKURU_EAST = "nakuru east"
    NAMAMALI = "namamali"
    NAMBALE_TOWNSHIP = "nambale township"
    NAMBOBOTO_NAMBUKU = "namboboto nambuku"
    NAMWELA = "namwela"
    NANAAM = "nanaam"
    NANDI_HILLS = "nandi hills"
    NANGINA = "nangina"
    NANIGHI = "nanighi"
    NANYUKI = "nanyuki"
    NAROK_TOWN = "narok town"
    NAROMORU_KIAMATHAGA = "naromoru kiamathaga"
    NDALANI = "ndalani"
    NDALAT = "ndalat"
    NDALU_TABANI = "ndalu/tabani"
    NDANAI_ABOSI = "ndanai/abosi"
    NDARAWETA = "ndaraweta"
    NDARUGU = "ndarugu"
    NDAVAYA = "ndavaya"
    NDEIYA = "ndeiya"
    NDENDERU = "ndenderu"
    NDITHINI = "ndithini"
    NDIVISI = "ndivisi"
    NDOTO = "ndoto"
    NDUMBERI = "ndumberi"
    NEBOI = "neboi"
    NESSUIT = "nessuit"
    NGANDO = "ngando"
    NGARA = "ngara"
    NGARE_MARA = "ngare mara"
    NGARIAMA = "ngariama"
    NGECHA_TIGONI = "ngecha tigoni"
    NGEI = "ngei"
    NGENDA = "ngenda"
    NGENYILEL = "ngenyilel"
    NGERIA = "ngeria"
    NGEWA = "ngewa"
    NGINDA_MANYATTA = "nginda-manyatta"
    NGINDA_MARAGWA = "nginda-maragwa"
    NGOBIT = "ngobit"
    NGOLIA = "ngolia"
    NGOLIBA = "ngoliba"
    NGOMENI = "ngomeni"
    NGONG = "ngong"
    NGUNI = "nguni"
    NGUUMO = "nguumo"
    NGUUTANI = "nguutani"
    NGUU_MASUMBA = "nguu/masumba"
    NG_ARARIA = "ng'araria"
    NJABINI_KIBURU = "njabini/kiburu"
    NJIA = "njia"
    NJIRU = "njiru"
    NJORO = "njoro"
    NJUKIINI = "njukiini"
    NKAIMURUNYA = "nkaimurunya"
    NKARETA = "nkareta"
    NKOMO = "nkomo"
    NKONDI = "nkondi"
    NKUENE = "nkuene"
    NORTH_ALEGO = "north alego"
    NORTH_EAST_BUNYORE = "north east bunyore"
    NORTH_GEM = "north gem"
    NORTH_HORR = "north horr"
    NORTH_KADEM = "north kadem"
    NORTH_KAMAGAMBO = "north kamagambo"
    NORTH_KANYAMKAGO = "north kanyamkago"
    NORTH_KARACHUONYO = "north karachuonyo"
    NORTH_KINANGOP = "north kinangop"
    NORTH_MARAGOLI = "north maragoli"
    NORTH_NYAKACH = "north nyakach"
    NORTH_SAKWA_AWENDO = "north sakwa"
    NORTH_SAKWA_BONDO = "north sakwa"
    NORTH_SEME = "north seme"
    NORTH_UGENYA = "north ugenya"
    NORTH_UYOMA = "north uyoma"
    NORTH_WEST_KISUMU = "north west kisumu"
    NTHAWA = "nthawa"
    NTIMARU_EAST = "ntimaru east"
    NTIMARU_WEST = "ntimaru west"
    NTIMA_EAST = "ntima east"
    NTIMA_WEST = "ntima west"
    NTUNENE = "ntunene"
    NUU = "nuu"
    NYABASI_EAST = "nyabasi east"
    NYABASI_WEST = "nyabasi west"
    NYACHEKI = "nyacheki"
    NYADHUNA = "nyadhuna"
    NYAKIO = "nyakio"
    NYAKI_EAST = "nyaki east"
    NYAKI_WEST = "nyaki west"
    NYAKOE = "nyakoe"
    NYALENDA_A = "nyalenda 'a'"
    NYALENDA_B = "nyalenda b"
    NYAMAIYA = "nyamaiya"
    NYAMASIBI = "nyamasibi"
    NYAMOSENSE_KOMOSOKO = "nyamosense/komosoko"
    NYANDUMA = "nyanduma"
    NYANGATI = "nyangati"
    NYANGORES = "nyangores"
    NYANSIONGO = "nyansiongo"
    NYATIEKO = "nyatieko"
    NYAYO_HIGHRISE = "nyayo highrise"
    NYIRO = "nyiro"
    NYOTA = "nyota"
    NZAMBANI = "nzambani"
    NZAUI_KILILI_KALAMBA = "nzaui/kilili/kalamba"
    NZOIA = "nzoia"
    OBBU = "obbu"
    OLDO_NYIRO = "oldo/nyiro"
    OLKARIA = "olkaria"
    OLKERI = "olkeri"
    OLOKURTO = "olokurto"
    OLOLMASANI = "ololmasani"
    OLOLULUNG_A = "ololulung'a"
    OLOOLUA = "oloolua"
    OLOOSIRKON_SHOLINKE = "oloosirkon/sholinke"
    OLORROPIL = "olorropil"
    OLPUSIMORU = "olpusimoru"
    OL_LESSOS = "ol'lessos"
    OL_MORAN = "ol-moran"
    OMBEYI = "ombeyi"
    ONGATA_RONGAI = "ongata rongai"
    PANGANI = "pangani"
    PARKLANDS_HIGHRIDGE = "parklands/highridge"
    PIPELINE = "pipeline"
    PONGWE_KIKONENI = "pongwe/kikoneni"
    PORO = "poro"
    PORT_REITZ = "port reitz"
    PUMA = "puma"
    PUMWANI = "pumwani"
    PURKO = "purko"
    RABAI_KISURUTINI = "rabai/kisurutini"
    RACECOURSE = "racecourse"
    RAGANA_ORUBA = "ragana-oruba"
    RAILWAYS = "railways"
    RAMISI = "ramisi"
    RAVINE = "ravine"
    RHAMU = "rhamu"
    RHAMU_DIMTU = "rhamu-dimtu"
    RHODA = "rhoda"
    RIABAI = "riabai"
    RIANA = "riana"
    RIBKWO = "ribkwo"
    RIGOMA = "rigoma"
    RIRUTA = "riruta"
    RIWO = "riwo"
    ROMBO = "rombo"
    RONGENA_MANARET = "rongena/manaret"
    RONG_E = "rong'e"
    ROYSAMBU = "roysambu"
    RUAI = "ruai"
    RUCHU = "ruchu"
    RUGI = "rugi"
    RUGURU = "ruguru"
    RUGURU_NGANDORI = "ruguru/ngandori"
    RUIRI_RWARERA = "ruiri/rwarera"
    RUMA_KAKSINGRI = "ruma-kaksingri"
    RUMURUTI_TOWNSHIP = "rumuruti township"
    RURII = "rurii"
    RURING_U = "ruring'u"
    RURUMA = "ruruma"
    RUSINGA_ISLAND = "rusinga island"
    RWARE = "rware"
    RWATHIA = "rwathia"
    SABAKI = "sabaki"
    SABENA = "sabena"
    SABOTI = "saboti"
    SACHO = "sacho"
    SAGALLA = "sagalla"
    SAGAMIAN = "sagamian"
    SAGANTE_JALDESA = "sagante/jaldesa"
    SAIMO_KIPSARAMAN = "saimo/kipsaraman"
    SAIMO_SOI = "saimo/soi"
    SAKA = "saka"
    SALAMA = "salama"
    SALA_BURA = "sala-bura"
    SALA_LAFEY = "sala-lafey"
    SAMBIRIR = "sambirir"
    SAMETA_MOKWERERO = "sameta/mokwerero"
    SANGAILU = "sangailu"
    SANGALO_KEBULONIK = "sangalo/kebulonik"
    SANGO = "sango"
    SANKURI = "sankuri"
    SARANGOMBE = "sarangombe"
    SARMAN = "sarman"
    SEGERA = "segera"
    SEGERO_BARSOMBE = "segero/barsombe"
    SEKERR = "sekerr"
    SENGWER = "sengwer"
    SENSI = "sensi"
    SERGOIT = "sergoit"
    SERICHO = "sericho"
    SHAABAB = "shaabab"
    SHAMAKHOKHO = "shamakhokho"
    SHAMATA = "shamata"
    SHANKOE = "shankoe"
    SHANZU = "shanzu"
    SHAURIMOYO_KALOLENI = "shaurimoyo kaloleni"
    SHELLA_LAMU_WEST = "shella-lamu west"
    SHELLA_MALINDI = "shella-malindi"
    SHEYWE = "sheywe"
    SHIKA_ADABU = "shika adabu"
    SHIMANZI_GANJONI = "shimanzi/ganjoni"
    SHIMBIR_FATUMA = "shimbir fatuma"
    SHIMO_LA_TEWA = "shimo la tewa"
    SHINOYI_SHIKOMARI_ESUMEYIA = "shinoyi-shikomari-esumeyia"
    SHIRERE = "shirere"
    SHIRU = "shiru"
    SHIRUGU_MUGAI = "shirugu-mugai"
    SIANA = "siana"
    SIAYA_TOWNSHIP = "siaya township"
    SIBOTI = "siboti"
    SIDINDI = "sidindi"
    SIGOMERE = "sigomere"
    SIGONA = "sigona"
    SIGOR = "sigor"
    SIGOWET = "sigowet"
    SIKHENDU = "sikhendu"
    SILALE = "silale"
    SILIBWET_TOWNSHIP = "silibwet township"
    SIMAT_KAPSERET = "simat/kapseret"
    SINGORWET = "singorwet"
    SINOKO = "sinoko"
    SINYERERE = "sinyerere"
    SIONGIROI = "siongiroi"
    SIRENDE = "sirende"
    SIRIKWA = "sirikwa"
    SITATUNGA = "sitatunga"
    SITIKHO = "sitikho"
    SIYOI = "siyoi"
    SOGOO = "sogoo"
    SOIN_RONGAI = "soin-rongai"
    SOIN_SIGOWET_SOIN = "soin-sigowet/soin"
    SOKOKE = "sokoke"
    SOKONI = "sokoni"
    SOLAI = "solai"
    SOLIAT = "soliat"
    SOLOLO = "sololo"
    SONGHOR_SOBA = "songhor/soba"
    SONGOT = "songot"
    SOOK = "sook"
    SOSIAN = "sosian"
    SOUTH_BUKUSU = "south bukusu"
    SOUTH_C = "south c"
    SOUTH_EAST_ALEGO = "south east alego"
    SOUTH_EAST_NYAKACH = "south east nyakach"
    SOUTH_GEM = "south gem"
    SOUTH_KABRAS = "south kabras"
    SOUTH_KAMAGAMBO = "south kamagambo"
    SOUTH_KANYAMKAGO = "south kanyamkago"
    SOUTH_KASIPUL = "south kasipul"
    SOUTH_MARAGOLI = "south maragoli"
    SOUTH_SAKWA_AWENDO = "south sakwa"
    SOUTH_SAKWA_BONDO = "south sakwa"
    SOUTH_UYOMA = "south uyoma"
    SOUTH_WEST_KISUMU = "south west kisumu"
    SOUTH_WEST_NYAKACH = "south west nyakach"
    SOY = "soy"
    SOYSAMBU_MITUA = "soysambu/mitua"
    SOY_NORTH = "soy north"
    SOY_SOUTH = "soy south"
    SUAM = "suam"
    SUBUKIA = "subukia"
    SUGUTA_MARMAR = "suguta marmar"
    SUNA_CENTRAL = "suna central"
    SUSWA = "suswa"
    SYOKIMAU_MULOLONGO = "syokimau/mulolongo"
    TABAKA = "tabaka"
    TAGARE = "tagare"
    TAKABA = "takaba"
    TAKABA_SOUTH = "takaba south"
    TALA = "tala"
    TAMBACH = "tambach"
    TAMBUA = "tambua"
    TANGULBEI_KOROSSI = "tangulbei/korossi"
    TAPACH = "tapach"
    TAPSAGOI = "tapsagoi"
    TARAKWA = "tarakwa"
    TARBAJ = "tarbaj"
    TEBERE = "tebere"
    TEBESONIK = "tebesonik"
    TEMBELIO = "tembelio"
    TENDENO_SORGET = "tendeno/sorget"
    TENGES = "tenges"
    TERIK = "terik"
    TEZO = "tezo"
    THANGATHA = "thangatha"
    THANGE = "thange"
    THARAKA = "tharaka"
    THEGU_RIVER = "thegu river"
    THETA = "theta"
    THIBA = "thiba"
    THINGITHU = "thingithu"
    TIGITHI = "tigithi"
    TIMAU = "timau"
    TIMBWANI = "timbwani"
    TINDIRET = "tindiret"
    TINET = "tinet"
    TING_ANG_A = "ting'ang'a"
    TIRIOKO = "tirioko"
    TIWI = "tiwi"
    TONGAREN = "tongaren"
    TONONOKA = "tononoka"
    TOWNSHIP_GARISSA_TOWNSHIP = "township-garissa township"
    TOWNSHIP_KANDUYI = "township-kanduyi"
    TOWNSHIP_KIAMBU = "township-kiambu"
    TOWNSHIP_KIHARU = "township-kiharu"
    TOWNSHIP_KITUI_CENTRAL = "township-kitui central"
    TOWNSHIP_MANDERA_EAST = "township-mandera east"
    TOWNSHIP_THIKA_TOWN = "township-thika town"
    TOWNSHIP_WAJIR_EAST = "township-wajir east"
    TOWNSHIP_WEST_MUGIRANGO = "township-west mugirango"
    TSEIKURU = "tseikuru"
    TSIMBA_GOLINI = "tsimba golini"
    TUDOR = "tudor"
    TULIMANI = "tulimani"
    TULWET_CHUIYAT = "tulwet/chuiyat"
    TURBI = "turbi"
    TURI = "turi"
    TURKWEL = "turkwel"
    TUWANI = "tuwani"
    UGUNJA = "ugunja"
    UKIA = "ukia"
    UKUNDA = "ukunda"
    UKWALA = "ukwala"
    UMANDE = "umande"
    UMOJA_I = "umoja i"
    UMOJA_II = "umoja ii"
    UPPER_KAEWA_IVETI = "upper kaewa/iveti"
    UPPER_SAVANNAH = "upper savannah"
    URAN = "uran"
    USONGA = "usonga"
    UTALII = "utalii"
    UTAWALA = "utawala"
    UTHIRU = "uthiru"
    UTHIRU_RUTHIMITU = "uthiru/ruthimitu"
    VANGA = "vanga"
    VISOI = "visoi"
    VIWANDANI_MAKADARA = "viwandani-makadara"
    VIWANDANI_NAIVASHA = "viwandani-naivasha"
    VOO_KYAMATU = "voo/kyamatu"
    WAA = "waa"
    WABERA = "wabera"
    WABERI = "waberi"
    WAGBERI = "wagberi"
    WAIA_KAKO = "waia-kako"
    WAITA = "waita"
    WAITALUK = "waitaluk"
    WAITHAKA = "waithaka"
    WALDAI = "waldai"
    WAMAGANA = "wamagana"
    WAMBA_EAST = "wamba east"
    WAMBA_NORTH = "wamba north"
    WAMBA_WEST = "wamba west"
    WAMUMU = "wamumu"
    WAMUNYU = "wamunyu"
    WANGCHIENG = "wangchieng"
    WANGU = "wangu"
    WANJOHI = "wanjohi"
    WARANQARA = "waranqara"
    WARGADUD_MANDERA_SOUTH = "wargadud-mandera south"
    WARGADUD_TARBAJ = "wargadud-tarbaj"
    WASEGES = "waseges"
    WASIMBETE = "wasimbete"
    WASO = "waso"
    WASWETA_II = "wasweta ii"
    WATAMU = "watamu"
    WAYU = "wayu"
    WEIWEI = "weiwei"
    WEMILABI = "wemilabi"
    WERU = "weru"
    WERUGHA = "werugha"
    WEST_ALEGO = "west alego"
    WEST_ASEMBO = "west asembo"
    WEST_BUKUSU = "west bukusu"
    WEST_BUNYORE = "west bunyore"
    WEST_GEM_GEM = "west gem"
    WEST_GEM_RANGWE = "west gem"
    WEST_KABRAS = "west kabras"
    WEST_KAMAGAK = "west kamagak"
    WEST_KANYAMKAGO = "west kanyamkago"
    WEST_KARACHUONYO = "west karachuonyo"
    WEST_KASIPUL = "west kasipul"
    WEST_KISUMU = "west kisumu"
    WEST_NALONDO = "west nalondo"
    WEST_NYAKACH = "west nyakach"
    WEST_SABATIA = "west sabatia"
    WEST_SAKWA_AWENDO = "west sakwa"
    WEST_SAKWA_BONDO = "west sakwa"
    WEST_SANG_ALO = "west sang'alo"
    WEST_SEME = "west seme"
    WEST_UGENYA = "west ugenya"
    WEST_UYOMA = "west uyoma"
    WEST_YIMBO = "west yimbo"
    WIGA = "wiga"
    WITEITHIE = "witeithie"
    WITU = "witu"
    WODANGA = "wodanga"
    WOODLEY_KENYATTA_GOLF_COURSE = "woodley/kenyatta golf course"
    WOTE = "wote"
    WUMINGU_KISHUSHE = "wumingu/kishushe"
    WUNDANYI_MBALE = "wundanyi/mbale"
    WUSI_KISHAMBA = "wusi/kishamba"
    YALA_TOWNSHIP = "yala township"
    YIMBO_EAST = "yimbo east"
    ZIMMERMAN = "zimmerman"
    ZIWA = "ziwa"
    ZIWANI_KARIOKOR = "ziwani/kariokor"
    ZIWA_LA_NG_OMBE = "ziwa la ng'ombe"
    ZOMBE_MWITIKA = "zombe/mwitika"

    # Machakos wards -> consituency map
    # Todo: update the rest of the wards
    # WARD_TO_CONSTITUENCY_MAP = {
    #     KIVAA: MASINGA,
    #     MASINGA_CENTRAL: MASINGA,
    #     EKALAKALA: MASINGA,
    #     MUTHESYA: MASINGA,
    #     NDITHINI: MASINGA,
    #     NDALANI: YATTA,
    #     MATUU: YATTA,
    #     KITHIMANI: YATTA,
    #     IKOMBE: YATTA,
    #     KATANGI: YATTA,
    #     KANGUNDO_NORTH: KANGUNDO,
    #     KANGUNDO_CENTRAL: KANGUNDO,
    #     KANGUNDO_EAST: KANGUNDO,
    #     KANGUNDO_WEST: KANGUNDO,
    #     MATUNGULU_NORTH: MATUNGULU,
    #     MATUNGULU_EAST: MATUNGULU,
    #     MATUNGULU_WEST: MATUNGULU,
    #     KYELENI: MATUNGULU,
    #     TALA: MATUNGULU,
    #     MITABONI: KATHIANI,
    #     KATHIANI_CENTRAL: KATHIANI,
    #     UPPER_KAEWA_IVETI: KATHIANI,
    #     LOWER_KAEWA_KAANI: KATHIANI,
    #     ATHI_RIVER: MAVOKO,
    #     KINANIE: MAVOKO,
    #     MUTHWANI: MAVOKO,
    #     SYOKIMAU_MULOLONGO: MAVOKO,
    #     KALAMA: MACHAKOS_TOWN,
    #     MUA: MACHAKOS_TOWN,
    #     MUTITUNI: MACHAKOS_TOWN,
    #     MACHAKOS_CENTRAL: MACHAKOS_TOWN,
    #     MUMBUNI_NORTH: MACHAKOS_TOWN,
    #     MUVUTINI_KIIMA_KIMWE: MACHAKOS_TOWN,
    #     KOLA: MACHAKOS_TOWN,
    #     MBIUNI: MWALA,
    #     MAKUTANO: MWALA,
    #     MASII: MWALA,
    #     MUTHETHENI: MWALA,
    #     WAMUNYU: MWALA,
    #     KIBAUNI: MWALA
    # }

    CONSTITUENCY_TO_COUNTY_MAP = {
        CHANGAMWE: MOMBASA,
        JOMVU: MOMBASA,
        KISAUNI: MOMBASA,
        NYALI: MOMBASA,
        LIKONI: MOMBASA,
        MVITA: MOMBASA,
        MSAMBWENI: KWALE,
        LUNGA_LUNGA: KWALE,
        MATUGA: KWALE,
        KINANGO: KWALE,
        KILIFI_NORTH: KILIFI,
        KILIFI_SOUTH: KILIFI,
        KALOLENI: KILIFI,
        RABAI: KILIFI,
        GANZE: KILIFI,
        MALINDI: KILIFI,
        MAGARINI: KILIFI,
        GARSEN: TANA_RIVER,
        GALOLE: TANA_RIVER,
        BURA: TANA_RIVER,
        LAMU_EAST: LAMU,
        LAMU_WEST: LAMU,
        TAVETA: TAITA_TAVETA,
        WUNDANYI: TAITA_TAVETA,
        MWATATE: TAITA_TAVETA,
        VOI: TAITA_TAVETA,
        GARISSA_TOWNSHIP: GARISSA,
        BALAMBALA: GARISSA,
        LAGDERA: GARISSA,
        DADAAB: GARISSA,
        FAFI: GARISSA,
        IJARA: GARISSA,
        WAJIR_NORTH: WAJIR,
        WAJIR_EAST: WAJIR,
        WAJIR_SOUTH: WAJIR,
        WAJIR_WEST: WAJIR,
        TARBAJ: WAJIR,
        ELDAS: WAJIR,
        MANDERA_WEST: MANDERA,
        BANISSA: MANDERA,
        MANDERA_NORTH: MANDERA,
        MANDERA_SOUTH: MANDERA,
        MANDERA_EAST: MANDERA,
        LAFEY: MANDERA,
        MOYALE: MARSABIT,
        NORTH_HORR: MARSABIT,
        SAKU: MARSABIT,
        LAISAMIS: MARSABIT,
        ISIOLO_NORTH: ISIOLO,
        ISIOLO_SOUTH: ISIOLO,
        IGEMBE_SOUTH: MERU,
        IGEMBE_CENTRAL: MERU,
        IGEMBE_NORTH: MERU,
        TIGANIA_WEST: MERU,
        TIGANIA_EAST: MERU,
        NORTH_IMENTI: MERU,
        BUURI: MERU,
        CENTRAL_IMENTI: MERU,
        SOUTH_IMENTI: MERU,
        MAARA: THARAKA_NITHI,
        CHUKA_IGAMBANG_OMBE: THARAKA_NITHI,
        THARAKA: THARAKA_NITHI,
        MANYATTA: EMBU,
        RUNYENJES: EMBU,
        MBEERE_SOUTH: EMBU,
        MBEERE_NORTH: EMBU,
        MWINGI_NORTH: KITUI,
        MWINGI_WEST: KITUI,
        MWINGI_CENTRAL: KITUI,
        KITUI_WEST: KITUI,
        KITUI_RURAL: KITUI,
        KITUI_CENTRAL: KITUI,
        KITUI_EAST: KITUI,
        KITUI_SOUTH: KITUI,
        MASINGA: MACHAKOS,
        YATTA: MACHAKOS,
        KANGUNDO: MACHAKOS,
        MATUNGULU: MACHAKOS,
        KATHIANI: MACHAKOS,
        MAVOKO: MACHAKOS,
        MACHAKOS_TOWN: MACHAKOS,
        MWALA: MACHAKOS,
        MBOONI: MAKUENI,
        KILOME: MAKUENI,
        KAITI: MAKUENI,
        MAKUENI: MAKUENI,
        KIBWEZI_WEST: MAKUENI,
        KIBWEZI_EAST: MAKUENI,
        KINANGOP: NYANDARUA,
        KIPIPIRI: NYANDARUA,
        OL_KALOU: NYANDARUA,
        OL_JOROK: NYANDARUA,
        NDARAGWA: NYANDARUA,
        TETU: NYERI,
        KIENI: NYERI,
        MATHIRA: NYERI,
        MATHIOYA: MURANGA,
        OTHAYA: NYERI,
        MUKURWEINI: NYERI,
        NYERI_TOWN: NYERI,
        MWEA: KIRINYAGA,
        GICHUGU: KIRINYAGA,
        NDIA: KIRINYAGA,
        KIRINYAGA_CENTRAL: KIRINYAGA,
        KANGEMA: MURANGA,
        KIHARU: MURANGA,
        KIGUMO: MURANGA,
        MARAGWA: MURANGA,
        KANDARA: MURANGA,
        GATANGA: MURANGA,
        GATUNDU_SOUTH: KIAMBU,
        GATUNDU_NORTH: KIAMBU,
        JUJA: KIAMBU,
        THIKA_TOWN: KIAMBU,
        RUIRU: KIAMBU,
        GITHUNGURI: KIAMBU,
        KIAMBU: KIAMBU,
        KIAMBAA: KIAMBU,
        KABETE: KIAMBU,
        KIKUYU: KIAMBU,
        LIMURU: KIAMBU,
        LARI: KIAMBU,
        TURKANA_NORTH: TURKANA,
        TURKANA_WEST: TURKANA,
        TURKANA_CENTRAL: TURKANA,
        LOIMA: TURKANA,
        TURKANA_SOUTH: TURKANA,
        TURKANA_EAST: TURKANA,
        KAPENGURIA: WEST_POKOT,
        SIGOR: WEST_POKOT,
        KACHELIBA: WEST_POKOT,
        POKOT_SOUTH: WEST_POKOT,
        SAMBURU_WEST: SAMBURU,
        SAMBURU_NORTH: SAMBURU,
        SAMBURU_EAST: SAMBURU,
        KWANZA: TRANS_NZOIA,
        ENDEBESS: TRANS_NZOIA,
        SABOTI: TRANS_NZOIA,
        KIMININI: TRANS_NZOIA,
        CHERANGANY: TRANS_NZOIA,
        SOY: UASIN_GISHU,
        TURBO: UASIN_GISHU,
        AINABKOI: UASIN_GISHU,
        KAPSERET: UASIN_GISHU,
        KESSES: UASIN_GISHU,
        MOIBEN: UASIN_GISHU,
        MARAKWET_EAST: ELGEYO_MARAKWET,
        MARAKWET_WEST: ELGEYO_MARAKWET,
        KEIYO_NORTH: ELGEYO_MARAKWET,
        KEIYO_SOUTH: ELGEYO_MARAKWET,
        TINDERET: NANDI,
        ALDAI: NANDI,
        NANDI_HILLS: NANDI,
        CHESUMEI: NANDI,
        EMGWEN: NANDI,
        MOSOP: NANDI,
        TIATY: BARINGO,
        BARINGO_NORTH: BARINGO,
        BARINGO_CENTRAL: BARINGO,
        BARINGO_SOUTH: BARINGO,
        MOGOTIO: BARINGO,
        ELDAMA_RAVINE: BARINGO,
        LAIKIPIA_WEST: LAIKIPIA,
        LAIKIPIA_EAST: LAIKIPIA,
        LAIKIPIA_NORTH: LAIKIPIA,
        MOLO: NAKURU,
        NJORO: NAKURU,
        NAIVASHA: NAKURU,
        GILGIL: NAKURU,
        KURESOI_SOUTH: NAKURU,
        KURESOI_NORTH: NAKURU,
        SUBUKIA: NAKURU,
        RONGAI: NAKURU,
        BAHATI: NAKURU,
        NAKURU_TOWN_WEST: NAKURU,
        NAKURU_TOWN_EAST: NAKURU,
        KILGORIS: NAROK,
        EMURUA_DIKIRR: NAROK,
        NAROK_NORTH: NAROK,
        NAROK_EAST: NAROK,
        NAROK_SOUTH: NAROK,
        NAROK_WEST: NAROK,
        KAJIADO_NORTH: KAJIADO,
        KAJIADO_CENTRAL: KAJIADO,
        KAJIADO_WEST: KAJIADO,
        KAJIADO_SOUTH: KAJIADO,
        KAJIADO_EAST: KAJIADO,
        KIPKELION_EAST: KERICHO,
        KIPKELION_WEST: KERICHO,
        AINAMOI: KERICHO,
        BURETI: KERICHO,
        BELGUT: KERICHO,
        SIGOWET_SOIN: KERICHO,
        SOTIK: BOMET,
        CHEPALUNGU: BOMET,
        BOMET_EAST: BOMET,
        BOMET_CENTRAL: BOMET,
        KONOIN: BOMET,
        LUGARI: KAKAMEGA,
        LIKUYANI: KAKAMEGA,
        MALAVA: KAKAMEGA,
        LURAMBI: KAKAMEGA,
        NAVAKHOLO: KAKAMEGA,
        MUMIAS_WEST: KAKAMEGA,
        MUMIAS_EAST: KAKAMEGA,
        MATUNGU: KAKAMEGA,
        BUTERE: KAKAMEGA,
        KHWISERO: KAKAMEGA,
        SHINYALU: KAKAMEGA,
        IKOLOMANI: KAKAMEGA,
        VIHIGA: VIHIGA,
        SABATIA: VIHIGA,
        HAMISI: VIHIGA,
        LUANDA: VIHIGA,
        EMUHAYA: VIHIGA,
        TESO_NORTH: BUSIA,
        TESO_SOUTH: BUSIA,
        NAMBALE: BUSIA,
        MATAYOS: BUSIA,
        BUTULA: BUSIA,
        FUNYULA: BUSIA,
        BUDALANGI: BUSIA,
        MT_ELGON: BUNGOMA,
        SIRISIA: BUNGOMA,
        KABUCHAI: BUNGOMA,
        BUMULA: BUNGOMA,
        KANDUYI: BUNGOMA,
        WEBUYE_EAST: BUNGOMA,
        WEBUYE_WEST: BUNGOMA,
        KIMILILI: BUNGOMA,
        TONGAREN: BUNGOMA,
        UGENYA: SIAYA,
        UGUNJA: SIAYA,
        ALEGO_USONGA: SIAYA,
        GEM: SIAYA,
        BONDO: SIAYA,
        RARIEDA: SIAYA,
        KISUMU_EAST: KISUMU,
        KISUMU_WEST: KISUMU,
        KISUMU_CENTRAL: KISUMU,
        SEME: KISUMU,
        NYANDO: KISUMU,
        MUHORONI: KISUMU,
        NYAKACH: KISUMU,
        KASIPUL: HOMA_BAY,
        KABONDO_KASIPUL: HOMA_BAY,
        KARACHUONYO: HOMA_BAY,
        RANGWE: HOMA_BAY,
        HOMA_BAY_TOWN: HOMA_BAY,
        NDHIWA: HOMA_BAY,
        SUBA_NORTH_MBITA: HOMA_BAY,
        SUBA_SOUTH: HOMA_BAY,
        RONGO: MIGORI,
        AWENDO: MIGORI,
        SUNA_EAST: MIGORI,
        SUNA_WEST: MIGORI,
        URIRI: MIGORI,
        NYATIKE: MIGORI,
        KURIA_WEST: MIGORI,
        KURIA_EAST: MIGORI,
        BONCHARI: KISII,
        SOUTH_MUGIRANGO: KISII,
        BOMACHOGE_BORABU: KISII,
        BOBASI: KISII,
        BOMACHOGE_CHACHE: KISII,
        NYARIBARI_MASABA: KISII,
        NYARIBARI_CHACHE: KISII,
        KITUTU_CHACHE_NORTH: KISII,
        KITUTU_CHACHE_SOUTH: KISII,
        KITUTU_MASABA: NYAMIRA,
        WEST_MUGIRANGO: NYAMIRA,
        NORTH_MUGIRANGO: NYAMIRA,
        BORABU: NYAMIRA,
        WESTLANDS: NAIROBI,
        DAGORETTI_NORTH: NAIROBI,
        DAGORETTI_SOUTH: NAIROBI,
        LANG_ATA: NAIROBI,
        KIBRA: NAIROBI,
        ROYSAMBU: NAIROBI,
        KASARANI: NAIROBI,
        RUARAKA: NAIROBI,
        EMBAKASI_SOUTH: NAIROBI,
        EMBAKASI_NORTH: NAIROBI,
        EMBAKASI_CENTRAL: NAIROBI,
        EMBAKASI_EAST: NAIROBI,
        EMBAKASI_WEST: NAIROBI,
        MAKADARA: NAIROBI,
        KAMUKUNJI: NAIROBI,
        STAREHE: NAIROBI,
        MATHARE: NAIROBI
    }

    # WARDS = list(WARD_TO_CONSTITUENCY_MAP.keys())

    CONSTITUENCIES = list(CONSTITUENCY_TO_COUNTY_MAP.keys())

    COUNTIES = list(set(CONSTITUENCY_TO_COUNTY_MAP.values()))
